name: PR Checks

on:
  pull_request:
    branches:
      - main  # Trigger the workflow when a pull request targets the 'main' branch

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run a simple linter (e.g., eslint, prettier, etc.)
        run: |
          # Example: Run a linter command (replace with your own tool)
          # You can add any command you want here, such as a linter, static analysis tool, etc.
          echo "Run your linter or other checks here"
